[package]
name = "simd-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "1", features = ["full", "parsing", "printing", "visit-mut", "extra-traits"] }
quote = "1"
